alter session set container = freepdb1;
create table test.users (
    id int,
    user_name varchar(256),
    email varchar(256),
    touch_count int default 0,
    last_update timestamp,
    primary key (id));

create table test.items (
    id int,
    item_name varchar(256),
    description varchar(512),
    touch_count int default 0,
    last_update timestamp,
    primary key (id));

create table test.likes (
    id int generated by default as identity,
    user_id int references test.users not null,
    item_id int references test.items not null,
    primary key (id));

insert into test.users (id, user_name, email)
    select id, user_name,
        user_name || '@' ||
               (case floor(dbms_random.value(0,4))
                   when 0 then 'gmail'
                   when 1 then 'hotmail'
                   when 2 then 'yahoo'
                   when 3 then 'yandex'
               end) || '.com' as email
    from (
        select rownum as id, dbms_random.string('x',10) as user_name
        from dual connect by level <= 100000
        );
commit;
insert into test.items (id, item_name, description)
    select rownum as id,
           'Item ' || dbms_random.string('x',10) as item_name,
           'Description ' || dbms_random.string('x',30) as description
    from dual connect by level <= 100000;
commit;
insert into test.likes (id, user_id, item_id)
    select rownum as id, user_id, item_id from (
    select distinct
       floor(dbms_random.value(2,100000)) as user_id,
       floor(dbms_random.value(2,100000)) as item_id
    from dual connect by level <= 500000)
    where user_id <> item_id;
commit;

--begin
--    DBMS_STATS.GATHER_TABLE_STATS(ownname => 'TEST', tabname  => 'ITEMS');
--end;
--/
--
