alter session set container = freepdb1;
create table test.users (
    id smallint,
    user_name varchar(256),
    email varchar(256),
    touch_count int default 0,
    last_update timestamp,
    primary key (id));

create table test.items (
    id int,
    item_name varchar(256),
    description varchar(512),
    touch_count int default 0,
    last_update timestamp,
    primary key (id));

create table test.likes (
    id int generated by default as identity,
    user_id int references test.users not null,
    item_id int references test.items not null,
    touch_count int default 0,
    last_update timestamp,
    primary key (id));

insert into test.users (id, user_name, email, last_update)
    select id, user_name,
        user_name || '@' ||
               (case floor(dbms_random.value(0,4))
                   when 0 then 'gmail'
                   when 1 then 'hotmail'
                   when 2 then 'yahoo'
                   when 3 then 'yandex'
               end) || '.com' as email,
               last_update
    from (
        select rownum as id, dbms_random.string('x',10) as user_name,
               TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2025-10-10','J'),TO_CHAR(DATE '2030-12-31','J'))),'J') as last_update
        from dual connect by level <= 100000
        );
commit;
insert into test.items (id, item_name, description)
    select rownum as id,
           'Item ' || dbms_random.string('x',10) as item_name,
           'Description ' || dbms_random.string('x',30) as description
    from dual connect by level <= 100000;
commit;
insert into test.likes (id, user_id, item_id, last_update)
    select rownum as id, user_id, item_id,
       TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(DATE '2025-10-10','J'),TO_CHAR(DATE '2030-12-31','J'))),'J') as last_update
    from (
    select distinct
       floor(dbms_random.value(2,100000)) as user_id,
       floor(dbms_random.value(2,100000)) as item_id
    from dual connect by level <= 500000)
    where user_id <> item_id;
commit;

create table test.to_list (
    id int,
    parent_id int,
    user_name varchar2(256),
    email varchar2(256),
    last_update timestamp);

insert into test.to_list (id, parent_id, user_name, email, last_update)
values (1, 1, 'user1', 'user1@gmail.com', to_timestamp('2025-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'));
commit;
