create PACKAGE BODY dbms_parallel_execute_i_b AS



  DEFAULT_MIN_BLOCKS  CONSTANT NUMBER := 50;
  ARG_TASK_NAME       CONSTANT VARCHAR2(10) := 'TASK_NAME';
  ARG_TASK_NAME_LEN   CONSTANT NUMBER := 128;
  ARG_COMMENT         CONSTANT VARCHAR2(10) := 'COMMENT';
  ARG_ERR_MSG         CONSTANT VARCHAR2(10) := 'ERR_MSG';
  ARG_VC2MAX_LEN      CONSTANT NUMBER := 4000;
  ARG_TABLE_OWNER     CONSTANT VARCHAR2(20) := 'TABLE_OWNER';
  ARG_TABLE_NAME      CONSTANT VARCHAR2(20) := 'TABLE_NAME';
  ARG_TABLE_COLUMN    CONSTANT VARCHAR2(20) := 'TABLE_COLUMN';
  ARG_OWNER_NAME      CONSTANT VARCHAR2(20) := 'OWNER_NAME';
  ARG_IDN_LEN         CONSTANT NUMBER := 30;




  P_JOB_NAME DBMS_ID;







  PROCEDURE SET_TASK_STATUS(OWNER#     IN NUMBER,
                            TASK       IN VARCHAR2,
                            NEW_STATUS IN NUMBER)
  IS
  BEGIN
    UPDATE DBMS_PARALLEL_EXECUTE_TASK$
      SET STATUS = NEW_STATUS
       WHERE TASK_OWNER# = OWNER#
         AND TASK_NAME   = TASK;
    COMMIT;
  END;



  FUNCTION IS_STOP_FLAG_SET(OWNER# IN NUMBER,
                            TASK   IN VARCHAR2)
  RETURN BOOLEAN
  IS
    L_FLAG NUMBER;
  BEGIN
    SELECT STOP_FLAG INTO L_FLAG
    FROM DBMS_PARALLEL_EXECUTE_TASK$
    WHERE TASK_OWNER# = OWNER#
      AND TASK_NAME   = TASK;

    IF (L_FLAG = 1) THEN
      RETURN TRUE;
    ELSE
      RETURN FALSE;
    END IF;
  END;



  PROCEDURE ASSERT_ARGUMENT_LENGTH(ARGV    IN VARCHAR2,
                                   ARGNM   IN VARCHAR2,
                                   MAXLEN  IN NUMBER,
                                   NULLCHK IN BOOLEAN DEFAULT FALSE)
  IS
  BEGIN
    IF ((ARGV IS NULL AND NULLCHK) OR LENGTHB(ARGV) > MAXLEN) THEN
      DBMS_SYS_ERROR.RAISE_SYSTEM_ERROR(-29496, ARGNM, MAXLEN);
    END IF;
  END;



  PROCEDURE ASSERT_TASK_EXISTS(OWNER# IN NUMBER,
                               TASK   IN VARCHAR2)
  IS
    CNT NUMBER;
  BEGIN
    ASSERT_ARGUMENT_LENGTH(TASK, ARG_TASK_NAME, ARG_TASK_NAME_LEN, TRUE);

    SELECT COUNT(*) INTO CNT
    FROM DBMS_PARALLEL_EXECUTE_TASK$
    WHERE TASK_OWNER# = OWNER#
      AND TASK_NAME   = TASK;

    IF (CNT <= 0) THEN
      RAISE DBMS_PARALLEL_EXECUTE_BUBLIK.TASK_NOT_FOUND;
    END IF;
  END;



  PROCEDURE ASSERT_CHUNK_EXISTS(OWNER# IN NUMBER,
                                TASK   IN VARCHAR2,
                                CHUNK  IN NUMBER)
  IS
    CNT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO CNT
    FROM DBMS_PARALLEL_EXECUTE_CHUNKS$
    WHERE TASK_OWNER# = OWNER#
      AND TASK_NAME   = TASK
      AND CHUNK_ID    = CHUNK;

    IF (CNT <= 0) THEN
      RAISE DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNK_NOT_FOUND;
    END IF;
  END;



  PROCEDURE STATUS_CHECK(STATUS IN NUMBER)
  IS
  BEGIN
    IF (STATUS != DBMS_PARALLEL_EXECUTE_BUBLIK.UNASSIGNED AND
        STATUS != DBMS_PARALLEL_EXECUTE_BUBLIK.ASSIGNED   AND
        STATUS != DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSED  AND
        STATUS != DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSED_WITH_ERROR) THEN
      RAISE DBMS_PARALLEL_EXECUTE_BUBLIK.INVALID_STATUS;
    END IF;
  END;









  FUNCTION GENERATE_TASK_NAME(PREFIX IN VARCHAR2 DEFAULT 'TASK$_')
  RETURN VARCHAR2
  IS
  BEGIN
    RETURN PREFIX||SEQ_NEXT_VAL;
  END;






  PROCEDURE CREATE_TASK(OWNER#     IN NUMBER,
                        TASK_NAME  IN VARCHAR2,
                        COMMENT    IN VARCHAR2 DEFAULT NULL)
  IS
    L_TASK_NAME VARCHAR2(128);
  BEGIN





    ASSERT_ARGUMENT_LENGTH(TASK_NAME, ARG_TASK_NAME, ARG_TASK_NAME_LEN, TRUE);
    ASSERT_ARGUMENT_LENGTH(COMMENT,   ARG_COMMENT,   ARG_VC2MAX_LEN);



    L_TASK_NAME := TASK_NAME;
    INSERT INTO DBMS_PARALLEL_EXECUTE_TASK$
      (TASK_OWNER#, TASK_NAME, CHUNK_TYPE, STATUS, CMT)
      VALUES(OWNER#, L_TASK_NAME, UNDECLARED, DBMS_PARALLEL_EXECUTE_BUBLIK.CREATED,
             COMMENT);
    COMMIT;
  EXCEPTION



    WHEN DUP_VAL_ON_INDEX THEN RAISE DBMS_PARALLEL_EXECUTE_BUBLIK.DUPLICATE_TASK_NAME;
    WHEN OTHERS           THEN RAISE;
  END;






  PROCEDURE DROP_TASK(OWNER#    IN NUMBER,
                      TASK_NAME IN VARCHAR2)
  IS
    L_TASK_NAME VARCHAR2(128);
    R_TASK_NAME VARCHAR2(128);
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);

    L_TASK_NAME := TASK_NAME;
    DELETE FROM DBMS_PARALLEL_EXECUTE_TASK$
      WHERE TASK_OWNER# = OWNER# AND TASK_NAME = L_TASK_NAME
      RETURNING TASK_NAME INTO R_TASK_NAME;

    COMMIT;
  END;












  PROCEDURE CREATE_CHUNKS_BY_ROWID(OWNER#      IN NUMBER,
                                   TASK_NAME   IN VARCHAR2,
                                   TABLE_OWNER IN VARCHAR2,
                                   TABLE_NAME  IN VARCHAR2,
                                   NUM_ROW     IN NUMBER)
  IS
    L_AVG_ROW_LEN NUMBER;
    L_BLOCKS      NUMBER;
    L_DB_BK_SIZE  NUMBER;
    L_TABLE_OWNER DBMS_ID;
    L_TABLE_NAME  DBMS_ID;
  BEGIN
    L_TABLE_OWNER := TABLE_OWNER;
    L_TABLE_NAME  := TABLE_NAME;










    SELECT  NVL(T.AVG_ROW_LEN, 0) INTO L_AVG_ROW_LEN
      FROM  DBA_TABLES T
      WHERE T.OWNER      = L_TABLE_OWNER
        AND T.TABLE_NAME = L_TABLE_NAME;


    SELECT VALUE INTO L_DB_BK_SIZE
      FROM V$PARAMETER
      WHERE UPPER(NAME) = 'DB_BLOCK_SIZE';


    L_BLOCKS := ROUND((NUM_ROW*L_AVG_ROW_LEN)/ L_DB_BK_SIZE, -1);
    IF (L_BLOCKS < DEFAULT_MIN_BLOCKS) THEN
        L_BLOCKS := DEFAULT_MIN_BLOCKS;
    END IF;


    CREATE_CHUNKS_BY_ROWID(OWNER#, TASK_NAME, TABLE_OWNER, TABLE_NAME,
                           NUM_BLOCK=>L_BLOCKS);
  END;





   PROCEDURE CREATE_CHUNKS_BY_ROWID(OWNER#     IN NUMBER,
                                    TASK_NAME   IN VARCHAR2,
                                    TABLE_OWNER IN VARCHAR2,
                                    TABLE_NAME  IN VARCHAR2,
                                    NUM_BLOCK   IN NUMBER)
  IS
    L_TASK_NAME   VARCHAR2(128);
    L_MAXBLOCKS   NUMBER;
    L_NUM_CHUNKS  NUMBER;
    L_CNT         NUMBER := 0;
    L_SEQ         NUMBER;
    L_START_BLK   NUMBER;
    L_END_BLK     NUMBER;
    L_START_ROWID ROWID;
    L_END_ROWID   ROWID;
    L_TABLE_OWNER DBMS_ID;
    L_TABLE_NAME  DBMS_ID;
    L_STATUS      NUMBER;
    L_BLOCKS      NUMBER;

    CURSOR C_EXT IS
      SELECT E.SEGMENT_NAME,
             E.PARTITION_NAME,
             E.SEGMENT_TYPE,
             E.DATA_OBJECT_ID,
             E.RELATIVE_FNO,
             E.BLOCK_ID,
             E.BLOCKS
      FROM   SYS.DBMS_PARALLEL_EXECUTE_EXTENTS E
      WHERE  E.OWNER        = TABLE_OWNER
      AND    E.SEGMENT_NAME = TABLE_NAME
      AND    E.SEGMENT_TYPE IN ('TABLE', 'TABLE PARTITION',
                                'TABLE SUBPARTITION')
      ORDER BY SEGMENT_NAME, PARTITION_NAME, RELATIVE_FNO, BLOCK_ID;
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);

    L_TASK_NAME   := TASK_NAME;
    L_TABLE_NAME  := TABLE_NAME;
    L_TABLE_OWNER := TABLE_OWNER;




    L_BLOCKS := NUM_BLOCK;
    IF (L_BLOCKS < DEFAULT_MIN_BLOCKS) THEN
        L_BLOCKS := DEFAULT_MIN_BLOCKS;
    END IF;




    UPDATE DBMS_PARALLEL_EXECUTE_TASK$
      SET STATUS      = DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING,
          CHUNK_TYPE  = ROWID_RANGE,
          TABLE_OWNER = L_TABLE_OWNER,
          TABLE_NAME  = L_TABLE_NAME
       WHERE TASK_OWNER# = OWNER#
         AND TASK_NAME   = L_TASK_NAME
         AND STATUS      IN (DBMS_PARALLEL_EXECUTE_BUBLIK.CREATED,
                             DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING_FAILED)
      RETURNING STATUS INTO L_STATUS;



    IF (L_STATUS IS NULL) THEN
      RAISE DBMS_PARALLEL_EXECUTE_BUBLIK.INVALID_STATE_FOR_CHUNK;
    END IF;


    DELETE FROM DBMS_PARALLEL_EXECUTE_CHUNKS$
      WHERE TASK_OWNER# = OWNER#
        AND TASK_NAME   = L_TASK_NAME;
    COMMIT;



    BEGIN







      FOR EREC IN C_EXT
      LOOP

         IF (EREC.BLOCKS > 0) THEN
            L_MAXBLOCKS := EREC.BLOCK_ID + EREC.BLOCKS - 1;
         ELSE
            L_MAXBLOCKS := EREC.BLOCK_ID;
         END IF;


         L_NUM_CHUNKS := ROUND(EREC.BLOCKS/L_BLOCKS + 0.5);


         L_CNT := 1;
         LOOP
            EXIT WHEN (L_CNT > L_NUM_CHUNKS);





            L_START_BLK := EREC.BLOCK_ID + (L_CNT - 1)*L_BLOCKS;
            L_END_BLK   := LEAST(L_MAXBLOCKS, EREC.BLOCK_ID+L_CNT*L_BLOCKS-1);

            L_START_ROWID :=  DBMS_ROWID.ROWID_CREATE(1,
                                                      EREC.DATA_OBJECT_ID,
                                                      EREC.RELATIVE_FNO,
                                                      L_START_BLK,
                                                      0);

            L_END_ROWID   :=  DBMS_ROWID.ROWID_CREATE(1,
                                                      EREC.DATA_OBJECT_ID,
                                                      EREC.RELATIVE_FNO,
                                                      L_END_BLK,
                                                      9999);


            L_SEQ := SEQ_NEXT_VAL;
            INSERT INTO DBMS_PARALLEL_EXECUTE_CHUNKS$(
              CHUNK_ID, TASK_OWNER#, TASK_NAME, STATUS, START_ROWID, END_ROWID)
              VALUES(L_SEQ, OWNER#, TASK_NAME,
                     DBMS_PARALLEL_EXECUTE_BUBLIK.UNASSIGNED,
                     L_START_ROWID, L_END_ROWID);
            COMMIT;

            L_CNT := L_CNT + 1;
         END LOOP;
      END LOOP;



      IF (L_CNT <= 1) THEN
        SET_TASK_STATUS(OWNER#, TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.NO_CHUNKS);
      ELSE
        SET_TASK_STATUS(OWNER#, TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKED);
      END IF;

    EXCEPTION WHEN OTHERS THEN

      SET_TASK_STATUS(OWNER#, TASK_NAME,DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING_FAILED);
      RAISE;
    END;
  END;





  PROCEDURE CREATE_CHUNKS_BY_NUMBER_COL(OWNER#       IN NUMBER,
                                        TASK_NAME    IN VARCHAR2,
                                        TABLE_OWNER  IN VARCHAR2,
                                        TABLE_NAME   IN VARCHAR2,
                                        TABLE_COLUMN IN VARCHAR2,
                                        CHUNK_SIZE   IN NUMBER)
  IS
    L_TASK_NAME   VARCHAR2(128);
    L_MIN_VAL     NUMBER;
    L_MAX_VAL     NUMBER;
    L_TBL_OWN     DBMS_ID;
    L_TBL_NM      DBMS_ID;
    L_COL_NM      DBMS_ID;
    L_AST_TBL_OWN DBMS_QUOTED_ID;
    L_AST_TBL_NM  DBMS_QUOTED_ID;
    L_AST_COL_NM  DBMS_QUOTED_ID;
    L_SQL         VARCHAR2(1000);
    L_START_ID    NUMBER;
    L_END_ID      NUMBER;
    L_SEQ         NUMBER;
    L_USR_CUR     INTEGER;
    L_ROWS        NUMBER;
    L_STATUS      NUMBER;
    L_CHUNK_SIZE  NUMBER;
    L_CNT         NUMBER := 0;
  BEGIN



    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);
    ASSERT_ARGUMENT_LENGTH(TABLE_OWNER,  ARG_TABLE_OWNER,  ARG_IDN_LEN, TRUE);
    ASSERT_ARGUMENT_LENGTH(TABLE_NAME,   ARG_TABLE_NAME,   ARG_IDN_LEN, TRUE);
    ASSERT_ARGUMENT_LENGTH(TABLE_COLUMN, ARG_TABLE_COLUMN, ARG_IDN_LEN, TRUE);

    L_AST_TBL_NM  := DBMS_ASSERT.ENQUOTE_NAME(TABLE_NAME,   FALSE);
    L_AST_TBL_OWN := DBMS_ASSERT.ENQUOTE_NAME(TABLE_OWNER,  FALSE);
    L_AST_COL_NM  := DBMS_ASSERT.ENQUOTE_NAME(TABLE_COLUMN, FALSE);
    L_CHUNK_SIZE := CHUNK_SIZE;
    IF (L_CHUNK_SIZE < 1) THEN L_CHUNK_SIZE := 1; END IF;


    L_TASK_NAME := TASK_NAME;
    L_TBL_NM    := TABLE_NAME;
    L_TBL_OWN   := TABLE_OWNER;
    L_COL_NM    := TABLE_COLUMN;
    UPDATE DBMS_PARALLEL_EXECUTE_TASK$
      SET STATUS        = DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING,
          CHUNK_TYPE    = NUMBER_RANGE,
          TABLE_OWNER   = L_TBL_OWN,
          TABLE_NAME    = L_TBL_NM,
          NUMBER_COLUMN = L_COL_NM
       WHERE TASK_OWNER# = OWNER#
         AND TASK_NAME   = L_TASK_NAME
         AND STATUS      IN (DBMS_PARALLEL_EXECUTE_BUBLIK.CREATED,
                             DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING_FAILED)
      RETURNING STATUS INTO L_STATUS;



    IF (L_STATUS IS NULL) THEN
      RAISE DBMS_PARALLEL_EXECUTE_BUBLIK.INVALID_STATE_FOR_CHUNK;
    END IF;


    DELETE FROM DBMS_PARALLEL_EXECUTE_CHUNKS$
      WHERE TASK_OWNER# = OWNER#
        AND TASK_NAME   = L_TASK_NAME;
    COMMIT;



    BEGIN














      L_SQL     := 'select min('||L_AST_COL_NM||'), max('||L_AST_COL_NM||')
                    from ' || L_AST_TBL_OWN || '.' || L_AST_TBL_NM;
      L_USR_CUR := DBMS_SYS_SQL.OPEN_CURSOR;
      DBMS_SYS_SQL.PARSE_AS_USER(L_USR_CUR, L_SQL, DBMS_SQL.NATIVE, OWNER#);
      DBMS_SYS_SQL.DEFINE_COLUMN(L_USR_CUR, 1, L_MIN_VAL);
      DBMS_SYS_SQL.DEFINE_COLUMN(L_USR_CUR, 2, L_MAX_VAL);

      L_ROWS := DBMS_SYS_SQL.EXECUTE_AND_FETCH(L_USR_CUR);
      DBMS_SYS_SQL.COLUMN_VALUE(L_USR_CUR, 1, L_MIN_VAL);
      DBMS_SYS_SQL.COLUMN_VALUE(L_USR_CUR, 2, L_MAX_VAL);


      IF (L_MIN_VAL IS NULL OR L_MAX_VAL IS NULL) THEN
        RETURN;
      END IF;


      L_END_ID := L_MIN_VAL-1;
      LOOP

        L_START_ID := L_END_ID + 1;
        L_END_ID   := LEAST(L_MAX_VAL, L_START_ID + L_CHUNK_SIZE - 1);


        L_SEQ := SEQ_NEXT_VAL;
        INSERT INTO DBMS_PARALLEL_EXECUTE_CHUNKS$(
          CHUNK_ID, TASK_OWNER#, TASK_NAME, STATUS, START_ID, END_ID)
          VALUES(L_SEQ, OWNER#, L_TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.UNASSIGNED,
                 L_START_ID, L_END_ID);
        COMMIT;
        L_CNT := L_CNT + 1;


        IF (L_END_ID = L_MAX_VAL) THEN
          EXIT;
        END IF;
      END LOOP;


      IF (L_CNT = 0) THEN
        SET_TASK_STATUS(OWNER#, L_TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.NO_CHUNKS);
      ELSE
        SET_TASK_STATUS(OWNER#, L_TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKED);
      END IF;

    EXCEPTION WHEN OTHERS THEN

      SET_TASK_STATUS(OWNER#, L_TASK_NAME,
                      DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING_FAILED);
      RAISE;
    END;
  END;






  PROCEDURE CREATE_CHUNKS_BY_SQL(OWNER#    IN NUMBER,
                                 TASK_NAME IN VARCHAR2,
                                 SQL_STMT  IN CLOB,
                                 BY_ROWID  IN BOOLEAN)
  IS
    L_TASK_NAME     VARCHAR2(128);
    L_CHUNK_TYPE    NUMBER;
    L_START_ID      NUMBER;
    L_END_ID        NUMBER;
    L_START_ROWID   UROWID;
    L_END_ROWID     UROWID;
    L_SEQ           NUMBER;
    L_SOURCE_CURSOR INTEGER;
    L_IGNORE        NUMBER;
    L_STATUS        NUMBER;
    L_CNT           NUMBER := 0;
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);

    L_TASK_NAME := TASK_NAME;


    IF (BY_ROWID = TRUE) THEN L_CHUNK_TYPE := ROWID_RANGE;
    ELSE                      L_CHUNK_TYPE := NUMBER_RANGE;  END IF;

    UPDATE DBMS_PARALLEL_EXECUTE_TASK$
      SET STATUS         = DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING,
          CHUNK_TYPE     = L_CHUNK_TYPE
       WHERE TASK_OWNER# = OWNER#
         AND TASK_NAME   = L_TASK_NAME
         AND STATUS      = DBMS_PARALLEL_EXECUTE_BUBLIK.CREATED
      RETURNING STATUS INTO L_STATUS;


    IF (L_STATUS IS NULL) THEN
      RAISE DBMS_PARALLEL_EXECUTE_BUBLIK.INVALID_STATE_FOR_CHUNK;
    END IF;

    COMMIT;



    BEGIN

      L_SOURCE_CURSOR := DBMS_SYS_SQL.OPEN_CURSOR;
      DBMS_SYS_SQL.PARSE_AS_USER(L_SOURCE_CURSOR, SQL_STMT, DBMS_SQL.NATIVE,
                                  OWNER#);
      IF (BY_ROWID = FALSE) THEN
        DBMS_SYS_SQL.DEFINE_COLUMN(L_SOURCE_CURSOR, 1, L_START_ID);
        DBMS_SYS_SQL.DEFINE_COLUMN(L_SOURCE_CURSOR, 2, L_END_ID);
      ELSE
        DBMS_SYS_SQL.DEFINE_COLUMN(L_SOURCE_CURSOR, 1, L_START_ROWID);
        DBMS_SYS_SQL.DEFINE_COLUMN(L_SOURCE_CURSOR, 2, L_END_ROWID);
      END IF;
      L_IGNORE := DBMS_SQL.EXECUTE(L_SOURCE_CURSOR);


      LOOP
         IF (DBMS_SYS_SQL.FETCH_ROWS(L_SOURCE_CURSOR)=0) THEN
           EXIT;
         END IF;


         IF (BY_ROWID = FALSE) THEN
           DBMS_SYS_SQL.COLUMN_VALUE(L_SOURCE_CURSOR, 1, L_START_ID);
           DBMS_SYS_SQL.COLUMN_VALUE(L_SOURCE_CURSOR, 2, L_END_ID);
         ELSE
           DBMS_SYS_SQL.COLUMN_VALUE(L_SOURCE_CURSOR, 1, L_START_ROWID);
           DBMS_SYS_SQL.COLUMN_VALUE(L_SOURCE_CURSOR, 2, L_END_ROWID);
         END IF;


         L_SEQ := SEQ_NEXT_VAL;
         INSERT INTO DBMS_PARALLEL_EXECUTE_CHUNKS$
           (CHUNK_ID, TASK_OWNER#, TASK_NAME, STATUS,
            START_ID, END_ID, START_ROWID, END_ROWID)
           VALUES (L_SEQ, OWNER#, L_TASK_NAME,
                   DBMS_PARALLEL_EXECUTE_BUBLIK.UNASSIGNED,
                   L_START_ID, L_END_ID, L_START_ROWID, L_END_ROWID);
         COMMIT;
         L_CNT := L_CNT + 1;
      END LOOP;


      DBMS_SYS_SQL.CLOSE_CURSOR(L_SOURCE_CURSOR);


      IF (L_CNT = 0) THEN
        SET_TASK_STATUS(OWNER#, L_TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.NO_CHUNKS);
      ELSE
        SET_TASK_STATUS(OWNER#, L_TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKED);
      END IF;

    EXCEPTION WHEN OTHERS THEN

      SET_TASK_STATUS(OWNER#, L_TASK_NAME,
                      DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING_FAILED);
      RAISE;
    END;
  END;






  PROCEDURE DROP_CHUNKS(OWNER#    IN NUMBER,
                        TASK_NAME IN VARCHAR2)
  IS
    L_TASK_NAME VARCHAR2(128);
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);

    L_TASK_NAME := TASK_NAME;

    DELETE FROM DBMS_PARALLEL_EXECUTE_CHUNKS$
      WHERE TASK_OWNER# = OWNER#
        AND TASK_NAME   = L_TASK_NAME;

    SET_TASK_STATUS(OWNER#, L_TASK_NAME, DBMS_PARALLEL_EXECUTE_BUBLIK.CREATED);

    COMMIT;
  END;







  FUNCTION GET_RANGE(OWNER#      IN  NUMBER,
                     TASK_NAME   IN  VARCHAR2,
                     CHUNK_ID    OUT NUMBER,
                     START_ROWID OUT ROWID,
                     END_ROWID   OUT ROWID,
                     START_ID    OUT NUMBER,
                     END_ID      OUT NUMBER)
  RETURN BOOLEAN
  IS
    L_TASK_NAME VARCHAR2(128);
    VAR_ROWID   ROWID;
    CURSOR GET_UNASSIGNED_CHUNKS IS
      SELECT ROWID
        FROM DBMS_PARALLEL_EXECUTE_CHUNKS$
        WHERE STATUS = DBMS_PARALLEL_EXECUTE_BUBLIK.UNASSIGNED
          AND TASK_OWNER# = OWNER#
          AND TASK_NAME = L_TASK_NAME
        FOR UPDATE SKIP LOCKED;
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);

    L_TASK_NAME := TASK_NAME;












    BEGIN
      OPEN GET_UNASSIGNED_CHUNKS;
      FETCH GET_UNASSIGNED_CHUNKS INTO VAR_ROWID;
      CLOSE GET_UNASSIGNED_CHUNKS;

      UPDATE DBMS_PARALLEL_EXECUTE_CHUNKS$
        SET STATUS = DBMS_PARALLEL_EXECUTE_BUBLIK.ASSIGNED,
            START_TS = SYSTIMESTAMP,
            END_TS = NULL,
            JOB_NAME = P_JOB_NAME
        WHERE ROWID = VAR_ROWID
        RETURNING CHUNK_ID, START_ROWID, END_ROWID, START_ID, END_ID
        INTO      CHUNK_ID, START_ROWID, END_ROWID, START_ID, END_ID;
      COMMIT;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      IF GET_UNASSIGNED_CHUNKS%ISOPEN THEN
        CLOSE GET_UNASSIGNED_CHUNKS;
      END IF;
      CHUNK_ID := NULL;
    END;


    IF (CHUNK_ID IS NULL) THEN
      RETURN FALSE;
    END IF;
    RETURN TRUE;
  END;






  PROCEDURE SET_CHUNK_STATUS(OWNER#    IN NUMBER,
                             TASK_NAME IN VARCHAR2,
                             CHUNK_ID  IN NUMBER,
                             STATUS    IN NUMBER,
                             ERR_NUM   IN NUMBER   DEFAULT NULL,
                             ERR_MSG   IN VARCHAR2 DEFAULT NULL)
  IS
    L_STMT VARCHAR2(1000);
  BEGIN




    STATUS_CHECK(STATUS);
    ASSERT_CHUNK_EXISTS(OWNER#, TASK_NAME, CHUNK_ID);
    ASSERT_ARGUMENT_LENGTH(ERR_MSG, ARG_ERR_MSG, ARG_VC2MAX_LEN);

    L_STMT := 'update DBMS_PARALLEL_EXECUTE_CHUNKS$
                 set status        = :1,
                     error_code    = :2,
                     error_message = :3,';







    IF    (STATUS = DBMS_PARALLEL_EXECUTE_BUBLIK.UNASSIGNED) THEN
      L_STMT := L_STMT || 'START_TS = NULL,         END_TS = NULL';
    ELSIF (STATUS = DBMS_PARALLEL_EXECUTE_BUBLIK.ASSIGNED)   THEN
      L_STMT := L_STMT || 'START_TS = systimestamp, END_TS = NULL';
    ELSE
      L_STMT := L_STMT || 'END_TS   = systimestamp';
    END IF;

    L_STMT := L_STMT || ' where task_owner# = :4
                            and task_name   = :5
                            and chunk_id    = :6';
    EXECUTE IMMEDIATE L_STMT USING STATUS,ERR_NUM,ERR_MSG,OWNER#,TASK_NAME,
                                   CHUNK_ID;
    COMMIT;
  END;






  PROCEDURE UNASSIGN_CHUNKS(OWNER#    IN NUMBER,
                            TASK_NAME IN VARCHAR2)
  IS
    L_TASK_NAME VARCHAR2(128);
  BEGIN
     L_TASK_NAME := TASK_NAME;

     UPDATE DBMS_PARALLEL_EXECUTE_CHUNKS$
      SET STATUS        = DBMS_PARALLEL_EXECUTE_BUBLIK.UNASSIGNED,
          JOB_NAME      = NULL,
          START_TS      = NULL,
          END_TS        = NULL,
          ERROR_CODE    = NULL,
          ERROR_MESSAGE = NULL
      WHERE TASK_OWNER# = OWNER#
        AND TASK_NAME   = L_TASK_NAME
        AND STATUS IN (DBMS_PARALLEL_EXECUTE_BUBLIK.ASSIGNED,
                       DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSED_WITH_ERROR);
    COMMIT;
  END;






  PROCEDURE PURGE_PROCESSED_CHUNKS(OWNER#    IN NUMBER,
                                   TASK_NAME IN VARCHAR2)
  IS
    L_TASK_NAME VARCHAR2(128);
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);

    DELETE FROM DBMS_PARALLEL_EXECUTE_CHUNKS$
      WHERE TASK_OWNER# = OWNER#
        AND TASK_NAME   = L_TASK_NAME
        AND (STATUS     = DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSED OR
             STATUS     = DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSED_WITH_ERROR);
    COMMIT;
  END;





  FUNCTION TASK_STATUS(OWNER#    IN NUMBER,
                       TASK_NAME IN VARCHAR2) RETURN NUMBER
  IS
    L_TASK_NAME VARCHAR2(128);
    L_STATUS    NUMBER;
    L_GETLCK    BOOLEAN;
    L_UNASSIGN  NUMBER;
    L_ASSIGNED  NUMBER;
    L_PROCESSED NUMBER;
    L_ERROR     NUMBER;
    L_TOTAL     NUMBER;
    L_JOB_PRE   DBMS_ID;
    L_JOB_CNT   PLS_INTEGER;
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);




    L_TASK_NAME := TASK_NAME;
    SELECT STATUS, JOB_PREFIX INTO L_STATUS, L_JOB_PRE
      FROM DBMS_PARALLEL_EXECUTE_TASK$
      WHERE TASK_OWNER# = OWNER#
        AND TASK_NAME = L_TASK_NAME;




    IF (L_STATUS = DBMS_PARALLEL_EXECUTE_BUBLIK.CREATED  OR
        L_STATUS = DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING OR
        L_STATUS = DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKING_FAILED) THEN
      RETURN L_STATUS;
    END IF;













    IF (L_JOB_PRE IS NOT NULL) THEN
      SELECT COUNT(*) INTO L_JOB_CNT
        FROM DBA_SCHEDULER_RUNNING_JOBS J,
             DBA_USERS                  U
        WHERE J.JOB_NAME LIKE L_JOB_PRE||'%'
          AND J.OWNER   = U.USERNAME
          AND U.USER_ID = OWNER#;
    END IF;

    SELECT * INTO L_UNASSIGN, L_ASSIGNED, L_PROCESSED, L_ERROR
      FROM (SELECT STATUS
            FROM DBMS_PARALLEL_EXECUTE_CHUNKS$
             WHERE TASK_OWNER# = OWNER#
               AND TASK_NAME   = L_TASK_NAME)
           PIVOT (COUNT(*) FOR STATUS IN (0,1,2,3));
    L_TOTAL := L_UNASSIGN + L_ASSIGNED + L_PROCESSED + L_ERROR;

    IF    (L_TOTAL             = 0) THEN
      RETURN DBMS_PARALLEL_EXECUTE_BUBLIK.NO_CHUNKS;
    ELSIF (L_UNASSIGN          = L_TOTAL) THEN
      RETURN DBMS_PARALLEL_EXECUTE_BUBLIK.CHUNKED;
    ELSIF (L_PROCESSED         = L_TOTAL) THEN
      RETURN DBMS_PARALLEL_EXECUTE_BUBLIK.FINISHED;
    ELSIF (L_ERROR+L_PROCESSED = L_TOTAL) THEN
      RETURN DBMS_PARALLEL_EXECUTE_BUBLIK.FINISHED_WITH_ERROR;
    ELSIF (L_JOB_CNT           = 0)       THEN
      RETURN DBMS_PARALLEL_EXECUTE_BUBLIK.CRASHED;
    ELSE
      RETURN DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSING;
    END IF;
  END;





  FUNCTION READ_TASK(OWNER# IN NUMBER,
                     TASK   IN VARCHAR2) RETURN TASK_TYPE
  IS
    RET TASK_TYPE;
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK);

    SELECT * INTO RET
    FROM DBMS_PARALLEL_EXECUTE_TASK$
    WHERE TASK_OWNER# = OWNER#
      AND TASK_NAME   = TASK;

    RETURN RET;
  END;





  PROCEDURE UPDATE_TASK(TASK TASK_TYPE)
  IS
  BEGIN
    UPDATE DBMS_PARALLEL_EXECUTE_TASK$
      SET CHUNK_TYPE                 = TASK.CHUNK_TYPE,
          STATUS                     = TASK.STATUS,
          TABLE_OWNER                = TASK.TABLE_OWNER,
          TABLE_NAME                 = TASK.TABLE_NAME,
          NUMBER_COLUMN              = TASK.NUMBER_COLUMN,
          CMT                        = TASK.CMT,
          JOB_PREFIX                 = TASK.JOB_PREFIX,
          STOP_FLAG                  = TASK.STOP_FLAG,
          SQL_STMT                   = TASK.SQL_STMT,
          LANGUAGE_FLAG              = TASK.LANGUAGE_FLAG,
          EDITION                    = TASK.EDITION,
          APPLY_CROSSEDITION_TRIGGER = TASK.APPLY_CROSSEDITION_TRIGGER,
          FIRE_APPLY_TRIGGER         = TASK.FIRE_APPLY_TRIGGER,
          PARALLEL_LEVEL             = TASK.PARALLEL_LEVEL,
          JOB_CLASS                  = TASK.JOB_CLASS
      WHERE TASK_OWNER# = TASK.TASK_OWNER#
        AND TASK_NAME   = TASK.TASK_NAME;

    COMMIT;
  END;




  FUNCTION SEQ_NEXT_VAL RETURN NUMBER
  IS
    L_VAL NUMBER;
  BEGIN
    SELECT DBMS_PARALLEL_EXECUTE_SEQ$.NEXTVAL INTO L_VAL FROM DUAL;
    RETURN L_VAL;
  END;





  PROCEDURE RUN_INTERNAL_WORKER(OWNER#    IN NUMBER,
                                TASK_NAME IN VARCHAR2,
                                JOB_NAME  IN VARCHAR2)
  IS
    L_START_ID           NUMBER;
    L_END_ID             NUMBER;
    L_START_ROWID        ROWID;
    L_END_ROWID          ROWID;
    L_ROWS_PROCESSED     NUMBER;
    L_CUR                INTEGER;
    L_FIRE_APPLY_TRIGGER BOOLEAN;
    L_CHUNK_ID           NUMBER;
    L_TASK               TASK_TYPE;
  BEGIN

    L_TASK := READ_TASK(OWNER#, TASK_NAME);


    IF (L_TASK.FIRE_APPLY_TRIGGER = 'TRUE') THEN L_FIRE_APPLY_TRIGGER := TRUE;
    ELSE                                         L_FIRE_APPLY_TRIGGER := FALSE;
    END IF;





    P_JOB_NAME := JOB_NAME;




    L_CUR := DBMS_SYS_SQL.OPEN_CURSOR;
    DBMS_SYS_SQL.PARSE_AS_USER(L_CUR,
                               DBMS_ASSERT.NOOP(L_TASK.SQL_STMT),
                               L_TASK.LANGUAGE_FLAG,
                               OWNER#,
                               FALSE,
                               L_TASK.EDITION,
                               L_TASK.APPLY_CROSSEDITION_TRIGGER,
                               L_FIRE_APPLY_TRIGGER);






    LOOP



        IF (IS_STOP_FLAG_SET(OWNER#, TASK_NAME)) THEN
          EXIT;
        END IF;





        IF (GET_RANGE(OWNER#, TASK_NAME, L_CHUNK_ID,
                      L_START_ROWID, L_END_ROWID, L_START_ID, L_END_ID)
            = FALSE) THEN
          EXIT;
        END IF;








        BEGIN
          IF (L_TASK.CHUNK_TYPE = ROWID_RANGE) THEN
            DBMS_SYS_SQL.BIND_VARIABLE(L_CUR, ':start_id', L_START_ROWID);
            DBMS_SYS_SQL.BIND_VARIABLE(L_CUR, ':end_id',   L_END_ROWID);
          ELSE
            DBMS_SYS_SQL.BIND_VARIABLE(L_CUR, ':start_id', L_START_ID);
            DBMS_SYS_SQL.BIND_VARIABLE(L_CUR, ':end_id',   L_END_ID);
          END IF;

          L_ROWS_PROCESSED := DBMS_SYS_SQL.EXECUTE(L_CUR);





          SET_CHUNK_STATUS(OWNER#, TASK_NAME, L_CHUNK_ID,
                           DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSED);
        EXCEPTION WHEN OTHERS THEN





          SET_CHUNK_STATUS(OWNER#, TASK_NAME, L_CHUNK_ID,
                           DBMS_PARALLEL_EXECUTE_BUBLIK.PROCESSED_WITH_ERROR,
                           SQLCODE, SQLERRM);
        END;




        COMMIT;
    END LOOP;




    DBMS_SYS_SQL.CLOSE_CURSOR(L_CUR);
  END;





  PROCEDURE STOP_TASK(OWNER#    IN NUMBER,
                      TASK_NAME IN VARCHAR2)
  IS
    L_TASK_NAME VARCHAR2(128);
    R_TASK_NAME VARCHAR2(128);
  BEGIN
    ASSERT_TASK_EXISTS(OWNER#, TASK_NAME);

    L_TASK_NAME := TASK_NAME;
    UPDATE DBMS_PARALLEL_EXECUTE_TASK$ T
      SET T.STOP_FLAG = 1
      WHERE T.TASK_OWNER# = OWNER#
        AND T.TASK_NAME   = L_TASK_NAME
      RETURNING T.TASK_NAME INTO R_TASK_NAME;

    COMMIT;
  END;


  FUNCTION OWNER_NAME_TO_NUM(OWNER_NAME IN VARCHAR2) RETURN NUMBER
  IS
    OWNER# NUMBER;
  BEGIN
    ASSERT_ARGUMENT_LENGTH(OWNER_NAME, ARG_OWNER_NAME, ARG_IDN_LEN, TRUE);

    SELECT USER_ID INTO OWNER#
      FROM DBA_USERS
      WHERE USERNAME = OWNER_NAME;

    RETURN OWNER#;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN DBMS_SYS_ERROR.RAISE_SYSTEM_ERROR(-12418,OWNER_NAME);
  WHEN OTHERS        THEN RAISE;
  END;



  PROCEDURE DROP_ALL_TASKS(OWNER_NAME IN VARCHAR2)
  IS
    L_OWN NUMBER;
  BEGIN
    L_OWN := OWNER_NAME_TO_NUM(OWNER_NAME);
    DELETE FROM DBMS_PARALLEL_EXECUTE_TASK$ WHERE TASK_OWNER# = L_OWN;
  END;



  FUNCTION DEFAULT_PARALLELISM RETURN PLS_INTEGER
  IS
     NUM_SLAVES PLS_INTEGER;
  BEGIN
     WITH
     INST_CPUS AS
        (SELECT INST_ID, NVL(TO_NUMBER(VALUE), 1) CPUS
            FROM  GV$PARAMETER
            WHERE NAME = 'cpu_count'),
     INST_THREADS AS
        (SELECT INST_ID, NVL(TO_NUMBER(VALUE), 1) CPU_THREADS
            FROM  GV$PARAMETER
            WHERE NAME = 'parallel_threads_per_cpu')
     SELECT SUM((CASE WHEN CPUS <= 0 THEN 1 ELSE CPUS END) *
                (CASE WHEN CPU_THREADS <= 0 THEN 1 ELSE CPU_THREADS END))
        INTO  NUM_SLAVES
        FROM  INST_CPUS, INST_THREADS
        WHERE INST_CPUS.INST_ID = INST_THREADS.INST_ID;


     IF (NUM_SLAVES IS NULL OR NUM_SLAVES <= 0) THEN
        NUM_SLAVES := 1;
     END IF;

     RETURN NUM_SLAVES;
  END;

END;
/
