threadCount: 2

fromProperties:
  url: jdbc:postgresql://localhost:5432/postgres?options=-c%20enable_indexscan=off%20-c%20enable_indexonlyscan=off%20-c%20enable_bitmapscan=off
  user: test
  password: test
toProperties:
  type: cassandra
  datacenter: datacenter1
  hosts: 172.28.0.1,172.28.0.2,172.28.0.3
  port: 9042
  keyspace: store
  user: test
  password: test
  batchSize: 256
