create table public.users (
    id int,
    user_name varchar,
    email varchar,
    touch_count int default 0,
    last_update timestamp,
    primary key (id));
create unique index on public.users (user_name);
create unique index on public.users (user_name, email);

create table public.items (
    id int,
    item_name varchar,
    description text,
    touch_count int default 0,
    last_update timestamp,
    primary key (id));
create unique index on public.items (item_name);

create table public.likes (
    id int generated by default as identity,
    user_id int references users,
    item_id int references items,
    touch_count int default 0,
    r char(200),
    last_update timestamp,
    primary key (id));
create unique index on public.likes (user_id, item_id);

insert into public.users (id, user_name, email)
    select id, user_name,
        user_name || '@' ||
               (case (random() * 3)::integer
                   when 0 then 'gmail'
                   when 1 then 'hotmail'
                   when 2 then 'yahoo'
                   when 3 then 'yandex'
               end) || '.com' as email
    from (
        select num as id, substr(md5(random()::text), 1, 10) as user_name
        from generate_series(1, 100000) as num
        );

insert into public.items (id, item_name, description)
    select num as id,
           'Item ' || substr(md5(random()::text), 1, 10) as item_name,
           'Description ' || substr(md5(random()::text), 1, 30) as description
    from generate_series(1, 100000) as num;

insert into public.likes (id, user_id, item_id, r)
    select num as id,
       floor(random() * 100000 + 1)::int as user_id,
       floor(random() * 100000 + 1)::int as item_id,
       rpad('Bublik is the best tool for migration ',50,'*') as r
    from generate_series(1, 1000000) as num
on conflict (user_id, item_id) do nothing;

analyze public.users;
analyze public.items;
analyze public.likes;
