<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.bublik</groupId>
        <artifactId>bublik</artifactId>
        <version>26.3.38</version>
    </parent>

    <artifactId>bublik-spring-boot-starter</artifactId>
    <packaging>jar</packaging>

    <developers>
        <developer>
            <name>Dmitrii Rudik</name>
            <email>dima.rudik@gmail.com</email>
            <organization>Bublik</organization>
            <organizationUrl>http://bublik.dev</organizationUrl>
        </developer>
    </developers>

    <name>bublik-spring-boot-starter</name>
    <description>Spring Boot Starter for Bublik: automated fault-tolerant data migration engine orchestration.</description>
    <url>https://github.com/dimarudik/bublik/tree/stable</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://opensource.org</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git://github.com/dimarudik/bublik.git</connection>
        <developerConnection>scm:git:ssh://github.com:dimarudik/bublik.git</developerConnection>
        <url>https://github.com/dimarudik/bublik/tree/stable</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <version>${spring-boot-configuration}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <version>${spring-boot-configuration}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-core</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-postgres</artifactId>
            <version>${project.parent.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-oracle</artifactId>
            <version>${project.parent.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-cassandra</artifactId>
            <version>${project.parent.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-clickhouse</artifactId>
            <version>${project.parent.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-mssql</artifactId>
            <version>${project.parent.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-kafka</artifactId>
            <version>${project.parent.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-ydb</artifactId>
            <version>${project.parent.version}</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <version>${spring-boot-configuration}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>4.0.0-M1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-postgres</artifactId>
            <version>${project.parent.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.bublik</groupId>
            <artifactId>bublik-oracle</artifactId>
            <version>${project.parent.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-postgresql</artifactId>
            <version>${testcontainers.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-oracle-free</artifactId>
            <version>${testcontainers.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${spring-boot-configuration}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>