package dev.bublik.starter.autoconfigure;

import dev.bublik.starter.properties.BublikProperties;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.testcontainers.containers.JdbcDatabaseContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.utility.DockerImageName;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class BublikStarterOracleToPostgresTest {
    static final OracleContainer oracle = new OracleContainer(
            DockerImageName.parse("gvenzl/oracle-free:slim-faststart"));

    static final JdbcDatabaseContainer<?> postgres = new PostgreSQLContainer<>(
            DockerImageName.parse("postgres"));

    @BeforeAll
    static void beforeAll() throws Exception {
        oracle.start();
        postgres.start();

        try (Connection conn = DriverManager.getConnection(oracle.getJdbcUrl(), oracle.getUsername(), oracle.getPassword());
             Statement stmt = conn.createStatement()) {

            stmt.execute("CREATE TABLE source_users (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(100))");
            stmt.execute("INSERT INTO source_users (name) VALUES ('Alice')");
            stmt.execute("INSERT INTO source_users (name) VALUES ('Bob')");
            stmt.execute("INSERT INTO source_users (name) VALUES ('Charlie')");
        }

        try (Connection conn = DriverManager.getConnection(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {

            stmt.execute("CREATE TABLE public.target_users (id INT PRIMARY KEY, name VARCHAR(100))");
        }
    }

    @AfterAll
    static void afterAll() {
        oracle.stop();
        postgres.stop();
    }

    @Test
    void shouldAutomaticallyMigrateDataFromOracleToPostgresOnStartup() {
        ApplicationContextRunner contextRunner = new ApplicationContextRunner()
                .withConfiguration(AutoConfigurations.of(BublikAutoConfiguration.class))
                .withPropertyValues(
                        "bublik.enabled=true",
                        "bublik.trigger-mode=ON_START",
                        "bublik.thread-count=2",

                        "bublik.from.url=" + oracle.getJdbcUrl(),
                        "bublik.from.user=" + oracle.getUsername(),
                        "bublik.from.password=" + oracle.getPassword(),

                        "bublik.to.url=" + postgres.getJdbcUrl(),
                        "bublik.to.user=" + postgres.getUsername(),
                        "bublik.to.password=" + postgres.getPassword(),

                        "bublik.pipelines[0].from-schema=" + oracle.getUsername().toUpperCase(), // В Oracle схема = Имя пользователя
                        "bublik.pipelines[0].from-table=SOURCE_USERS",
                        "bublik.pipelines[0].to-schema=public",
                        "bublik.pipelines[0].to-table=target_users"
                );

        contextRunner.run(context -> {
            assertThat(context).hasSingleBean(BublikAutoConfiguration.class);
            assertThat(context).hasSingleBean(BublikProperties.class);
            assertThat(context).hasBean("automatedMigrationRunner");

            ApplicationRunner runner = context.getBean(
                    "automatedMigrationRunner", org.springframework.boot.ApplicationRunner.class);

            System.out.println("[TEST] Triggering cold-start. Invoking Bublik automatedMigrationRunner...");

            runner.run(null);

            System.out.println("[TEST] Migration execution finished. Verifying rows inside target PostgreSQL СУБД...");

            try (Connection conn = DriverManager.getConnection(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
                 Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery("SELECT COUNT(*), MIN(name) FROM public.target_users")) {

                assertTrue(rs.next(), "Результат агрегации должен вернуть строку");
                int count = rs.getInt(1);
                String firstUser = rs.getString(2);

                assertEquals(3, count, "Количество перенесенных записей в PostgreSQL должно быть равно 3");
                assertEquals("Alice", firstUser, "Имена пользователей в результирующем Postgres должны совпадать с исходным Oracle");

                System.out.println("[TEST] GENIUS! Heterogeneous Oracle -> PostgreSQL migration via Spring Boot Starter is verified.");
            }
        });
    }

}
