CREATE TYPE role_status AS ENUM ('NotActive', 'Active', 'Closed');

create table public.t1 (
    id int,
    a varchar(256),
    b bigint,
    c bytea,
    d boolean,
    e date,
    f decimal,
    g double precision,
--    h duration,
    i float,
    j inet,
    k int,
    l smallint,
    m text,
    n time,
    o timestamp,
    p uuid,
    q int2,
    r uuid,
    s varchar(256),
    t bigint,
    u jsonb,
    mmap jsonb,
    set1 text[],
    list1 text[],
    status role_status);

create table public.t2 (
    id int,
    a varchar(256),
    b bigint,
    c bytea,
    d boolean,
    e date,
    f decimal,
    g double precision,
--    h duration,
    i float,
    j inet,
    k int,
    l smallint,
    m text,
    n time,
    o timestamp,
    p uuid,
    q int2,
    r uuid,
    s varchar(256),
    t bigint,
    u jsonb);
