package dev.bublik.oracle;

import com.clickhouse.client.api.Client;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import dev.bublik.clickhouse.storage.ClickHouseStorage;
import dev.bublik.core.model.Config;
import dev.bublik.core.model.PseudoTable;
import dev.bublik.core.model.Table;
import dev.bublik.core.storage.Storage;
import dev.bublik.oracle.storage.OracleStorage;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.clickhouse.ClickHouseContainer;
import org.testcontainers.containers.JdbcDatabaseContainer;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.utility.DockerImageName;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class ClickHouseMigrationTest {
    static final JdbcDatabaseContainer<?> oracle = new OracleContainer(
            DockerImageName.parse("gvenzl/oracle-free:slim-faststart"));

    private static final DockerImageName CLICKHOUSE_LATEST = DockerImageName
            .parse("clickhouse")
            .asCompatibleSubstituteFor("clickhouse/clickhouse-server");
    private static final ClickHouseContainer clickhouse = new ClickHouseContainer(CLICKHOUSE_LATEST);

    static HikariDataSource sourceDataSource;
    static Client clickhouseClient;

    @BeforeAll
    static void beforeAll() throws Exception {
        oracle.start();
        clickhouse.start();

        HikariConfig sourceConfig = new HikariConfig();
        sourceConfig.setJdbcUrl(oracle.getJdbcUrl());
        sourceConfig.setUsername(oracle.getUsername());
        sourceConfig.setPassword(oracle.getPassword());
        sourceConfig.setMaximumPoolSize(5);
        sourceDataSource = new HikariDataSource(sourceConfig);

        int expectedClickhousePoolSize = 5;
        String clickhouseHttpUrl = "http://" + clickhouse.getHost() + ":" + clickhouse.getMappedPort(8123);
        clickhouseClient = new Client.Builder()
                .addEndpoint(clickhouseHttpUrl)
                .setDefaultDatabase("default")
                .setUsername(clickhouse.getUsername())
                .setPassword(clickhouse.getPassword())
                .setMaxConnections(expectedClickhousePoolSize)
                .setConnectTimeout(10, ChronoUnit.SECONDS)
                .setSocketTimeout(5, ChronoUnit.MINUTES)
                .build();

        try (Connection conn = sourceDataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE source_users (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(100))");
            stmt.execute("INSERT INTO source_users (id, name) VALUES (1, 'Alice')");
            stmt.execute("INSERT INTO source_users (id, name) VALUES (2, 'Bob')");
            stmt.execute("INSERT INTO source_users (id, name) VALUES (3, 'Charlie')");
        }

        try (Connection conn = clickhouse.createConnection(""); Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE default.target_users (id Int32, name String) ENGINE = MergeTree() ORDER BY id");
        }
    }

    @AfterAll
    static void afterAll() throws Exception {
        if (sourceDataSource != null) sourceDataSource.close();
        if (clickhouseClient != null) clickhouseClient.close();
        oracle.stop();
        clickhouse.stop();
    }

    @Test
    void testOracleToClickHouseMigration() throws Exception {
        Table targetOutboxTable = new PseudoTable(null, "target_outbox");
        Storage sourceStorage = new OracleStorage(sourceDataSource);
        Storage targetStorage = new ClickHouseStorage(clickhouseClient, targetOutboxTable);

        assertEquals(5, targetStorage.getThreadCount(),
                "Количество потоков Бублика должно автоматически подстроиться под размер maxConnections нативного клиента ClickHouse");

        List<Config> configs = new ArrayList<>();
        Config tableConfig = new Config(
                oracle.getUsername().toUpperCase(),
                "SOURCE_USERS",
                "default",
                "target_users"
        );
        configs.add(tableConfig);

        sourceStorage.start(targetStorage, configs, 1000);

        try (Connection conn = clickhouse.createConnection("");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT count(), min(name) FROM default.target_users")) {

            assertTrue(rs.next());
            long count = rs.getLong(1);
            String firstUser = rs.getString(2);

            assertEquals(3, count, "Количество строк в ClickHouse должно быть равно 3");
            assertEquals("Alice", firstUser, "Имена пользователей на стороне ClickHouse должны совпадать с Oracle");
        }

        sourceStorage.closeStorage();
        targetStorage.closeStorage();
    }
}
