package dev.bublik.oracle;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import dev.bublik.core.model.Config;
import dev.bublik.core.model.PseudoTable;
import dev.bublik.core.model.Table;
import dev.bublik.core.storage.Storage;
import dev.bublik.oracle.storage.OracleStorage;
import dev.bublik.postgres.storage.PostgresStorage;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.JdbcDatabaseContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.utility.DockerImageName;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class PostgresMigrationTest {
    static final JdbcDatabaseContainer<?> oracle = new OracleContainer(
            DockerImageName.parse("gvenzl/oracle-free:slim-faststart"));

    static final JdbcDatabaseContainer<?> postgres = new PostgreSQLContainer<>(
            DockerImageName.parse("postgres"));

    static HikariDataSource sourceDataSource;
    static HikariDataSource targetDataSource;

    @BeforeAll
    static void beforeAll() throws Exception {
        oracle.start();
        postgres.start();

        HikariConfig sourceConfig = new HikariConfig();
        sourceConfig.setJdbcUrl(oracle.getJdbcUrl());
        sourceConfig.setUsername(oracle.getUsername());
        sourceConfig.setPassword(oracle.getPassword());
        sourceConfig.setMaximumPoolSize(5);
        sourceDataSource = new HikariDataSource(sourceConfig);

        HikariConfig targetConfig = new HikariConfig();
        targetConfig.setJdbcUrl(postgres.getJdbcUrl());
        targetConfig.setUsername(postgres.getUsername());
        targetConfig.setPassword(postgres.getPassword());
        targetConfig.setMaximumPoolSize(5);
        targetDataSource = new HikariDataSource(targetConfig);

        try (Connection conn = sourceDataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE source_users (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(100))");
            stmt.execute("CREATE TABLE target_users (id NUMBER PRIMARY KEY, name VARCHAR2(100))");

            stmt.execute("INSERT INTO source_users (id, name) VALUES (1, 'Alice')");
            stmt.execute("INSERT INTO source_users (id, name) VALUES (2, 'Bob')");
            stmt.execute("INSERT INTO source_users (id, name) VALUES (3, 'Charlie')");
        }

        try (Connection conn = targetDataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE target_users (id INT PRIMARY KEY, name VARCHAR(100))");
        }
    }

    @AfterAll
    static void afterAll() {
        if (sourceDataSource != null) sourceDataSource.close();
        if (targetDataSource != null) targetDataSource.close();
        oracle.stop();
        postgres.stop();
    }

    @Test
    void testOracleToOracleMigration() throws Exception {
        Table sourceOutboxTable = new PseudoTable(null, "foo");
        Table targetOutboxTable = new PseudoTable("public", "bublik");
        Storage sourceStorage = new OracleStorage(sourceDataSource, sourceOutboxTable);
        Storage targetStorage = new PostgresStorage(targetDataSource, targetOutboxTable);

        List<Config> configs = new ArrayList<>();
        Config tableConfig = new Config(
                oracle.getUsername().toUpperCase(),
                "SOURCE_USERS",
                "public",
                "target_users"
        );
        configs.add(tableConfig);

        sourceStorage.start(targetStorage, configs, 1000);

        try (Connection conn = targetDataSource.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*), MIN(name) FROM target_users")) {

            assertTrue(rs.next());
            int count = rs.getInt(1);
            String firstUser = rs.getString(2);

            assertEquals(3, count, "Количество перенесенных строк в Postgres должно быть равно 3");
            assertEquals("Alice", firstUser, "Данные внутри Postgres должны совпадать");
        }

        sourceStorage.closeStorage();
        targetStorage.closeStorage();
    }
}
