create role test with login superuser password 'test';
create type mood AS ENUM ('sad', 'ok', 'happy');
create type gender AS ENUM ('male', 'female', 'NA');

create table users (
    user_id int,
    user_name varchar,
    email varchar,
    primary key (user_id));
create unique index on users (user_name);

create table items (
    item_id int,
    item_name varchar,
    description text,
    primary key (item_id));
create unique index on items (item_name);

create table likes (
    like_id int generated by default as identity,
    user_id int references users,
    item_id int references items,
    primary key (like_id));
create unique index on likes (user_id, item_id);
